In [1]:
import numpy as np

In [2]:
def environment(tup, action):
    if (tup[0]==0 and action==1)or(tup[0]==3 and action==3)or(tup[1]==0 and action==0)or(tup[1]==3 and action==2):
        return tup
    if action==0:
        return (tup[0], tup[1]-1)
    elif action==1:
        return (tup[0]-1, tup[1])
    elif action==2:
        return (tup[0], tup[1]+1)
    elif action==3:
        return (tup[0]+1, tup[1])
    return

In [3]:
v_k = np.zeros((4,4))
v_k1 = np.zeros((4,4))

for k in range(300):
    for i in range(4):
        for j in range(4):
            if (i==0 and j==0) or (i==3 and j==3): continue
            else:
                sum_ = 0.0
                for a in range(4):
                    tup = environment((i,j),a)
                    sum_ += (-1 + v_k[tup])/4.0
                v_k1[i,j] = sum_
    if k>10:
        v_k = v_k1.copy()
        continue
    print('k = %d'%k)
    print(v_k)
    v_k = v_k1.copy()
print('k = inf')
print(v_k)

k = 0
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
k = 1
[[ 0. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1.  0.]]
k = 2
[[ 0.   -1.75 -2.   -2.  ]
 [-1.75 -2.   -2.   -2.  ]
 [-2.   -2.   -2.   -1.75]
 [-2.   -2.   -1.75  0.  ]]
k = 3
[[ 0.     -2.4375 -2.9375 -3.    ]
 [-2.4375 -2.875  -3.     -2.9375]
 [-2.9375 -3.     -2.875  -2.4375]
 [-3.     -2.9375 -2.4375  0.    ]]
k = 4
[[ 0.      -3.0625  -3.84375 -3.96875]
 [-3.0625  -3.71875 -3.90625 -3.84375]
 [-3.84375 -3.90625 -3.71875 -3.0625 ]
 [-3.96875 -3.84375 -3.0625   0.     ]]
k = 5
[[ 0.        -3.65625   -4.6953125 -4.90625  ]
 [-3.65625   -4.484375  -4.78125   -4.6953125]
 [-4.6953125 -4.78125   -4.484375  -3.65625  ]
 [-4.90625   -4.6953125 -3.65625    0.       ]]
k = 6
[[ 0.         -4.20898438 -5.50976562 -5.80078125]
 [-4.20898438 -5.21875    -5.58984375 -5.50976562]
 [-5.50976562 -5.58984375 -5.21875    -4.20898438]
 [-5.80078125 -5.50976562 -4.20898438  0.        ]]
k = 7
[[ 0.        