In [1]:
import numpy as np

In [2]:
def environment(tup, action):
    if (tup[0]==0 and action==1)or(tup[0]==3 and action==3)or(tup[1]==0 and action==0)or(tup[1]==3 and action==2):
        return tup
    if action==0:
        return (tup[0], tup[1]-1)
    elif action==1:
        return (tup[0]-1, tup[1])
    elif action==2:
        return (tup[0], tup[1]+1)
    elif action==3:
        return (tup[0]+1, tup[1])
    return

In [9]:
print('Synchronous')
v_k = np.zeros((4,4))
v_k1 = np.zeros((4,4))

for k in range(7):
    for i in range(4):
        for j in range(4):
            if (i==0 and j==0): continue
            else:
                max_num = -1000.0
                for action in range(4):
                    if -1.0 + v_k[environment((i,j), action)] > max_num:
                        max_num = -1.0 + v_k[environment((i,j), action)]
                        v_k1[i,j] = -1.0 + v_k[environment((i,j), action)]
    print(v_k)
    v_k = v_k1.copy()

Synchronous
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[ 0. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]]
[[ 0. -1. -2. -2.]
 [-1. -2. -2. -2.]
 [-2. -2. -2. -2.]
 [-2. -2. -2. -2.]]
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -3.]
 [-2. -3. -3. -3.]
 [-3. -3. -3. -3.]]
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -4.]
 [-2. -3. -4. -4.]
 [-3. -4. -4. -4.]]
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -4.]
 [-2. -3. -4. -5.]
 [-3. -4. -5. -5.]]
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -4.]
 [-2. -3. -4. -5.]
 [-3. -4. -5. -6.]]


In [10]:
print('Asynchronous')
v_k = np.zeros((4,4))

for k in range(7):
    for i in range(4):
        for j in range(4):
            if (i==0 and j==0): continue
            else:
                max_num = -1000.0
                for action in range(4):
                    if -1.0 + v_k[environment((i,j), action)] > max_num:
                        max_num = -1.0 + v_k[environment((i,j), action)]
                        v_k[i,j] = -1.0 + v_k[environment((i,j), action)]
    print(v_k)

Asynchronous
[[ 0. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -2.]]
[[ 0. -1. -2. -2.]
 [-1. -2. -2. -2.]
 [-2. -2. -2. -3.]
 [-2. -2. -3. -4.]]
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -4.]
 [-2. -3. -4. -5.]
 [-3. -4. -5. -6.]]
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -4.]
 [-2. -3. -4. -5.]
 [-3. -4. -5. -6.]]
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -4.]
 [-2. -3. -4. -5.]
 [-3. -4. -5. -6.]]
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -4.]
 [-2. -3. -4. -5.]
 [-3. -4. -5. -6.]]
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -4.]
 [-2. -3. -4. -5.]
 [-3. -4. -5. -6.]]
